import type { InternalProperty } from './types';

type CatalogEntry = Omit<
  InternalProperty,
  'id' | 'coverImageUrl' | 'checkinTime' | 'checkoutTime' | 'address' | 'latitude' | 'longitude'
> & { isVisible: boolean };

// Static enrichment data per Hostex property ID.
// coverImageUrl, checkinTime, checkoutTime, address, lat/lng come from Hostex API.
// Everything else is managed here until a proper CMS is in place.
export const PROPERTY_CATALOG: Record<number, CatalogEntry> = {
  12393467: {
    isVisible: true,
    slug: 'noviembre-20',
    name: 'N20 H1',
    shortDescription:
      'Departamento céntrico a 5 cuadras de CAXA. 1 habitación con cama matrimonial. Estacionamiento privado, WiFi rápido y espacio de trabajo.',
    description:
      'Descansa en este cómodo departamento ubicado en la colonia Modelo, a 5 cuadras de la Central de Autobuses CAXA. Cuenta con 1 habitación con cama matrimonial, estacionamiento privado, WiFi estable, espacio de trabajo y microondas. Zona residencial tranquila y segura, con tiendas, restaurantes y transporte a pasos. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Colonia Modelo',
    location: 'Colonia Modelo, Xalapa',
    pricePerNight: 549,
    cleaningFee: 200,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: [
      'WiFi',
      'Microondas',
      'Estacionamiento',
      'TV',
      'Espacio de trabajo',
      'Pet friendly',
    ],
    tags: ['céntrico', 'pareja', 'trabajo'],
  },
  12155809: {
    isVisible: true,
    slug: 'colina-2',
    name: 'Colina 2',
    shortDescription:
      'Departamento moderno y privado con garaje. 1 habitación con cama king size. Pet friendly, WiFi rápido y cocina equipada.',
    description:
      'La Unidad 2 del complejo Colina te ofrece una habitación con cama king size, cocina equipada con estufa, refrigerador, microondas y licuadora, además de estacionamiento privado. Ubicada en el 1er piso del edificio coral en la colonia Aguacatal, a 5 minutos del Mercado La Rotonda y 15 minutos del centro histórico. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 669,
    cleaningFee: 250,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 5,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'pareja'],
  },
  12155808: {
    isVisible: true,
    slug: 'colina-4',
    name: 'Colina 4',
    shortDescription:
      'Alojamiento ejecutivo y elegante para 1 a 4 personas. 2 habitaciones con 2 camas matrimoniales. Pet friendly y estacionamiento privado.',
    description:
      'La Unidad 4 de Colina es perfecta para familias o grupos pequeños. Con 2 habitaciones con camas matrimoniales, cocina equipada, sala amplia y estacionamiento privado. Ubicada en el 2do piso del edificio coral en Aguacatal. A 5 minutos del Mercado La Rotonda y 15 minutos del centro. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 669,
    cleaningFee: 250,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'familiar', 'pareja'],
  },
  12454379: {
    isVisible: true,
    slug: 'colina-5',
    name: 'Colina 5',
    shortDescription:
      'Departamento para grupos grandes, ideal para 2 a 7 personas. 2 habitaciones con 4 camas matrimoniales. Pet friendly y estacionamiento privado.',
    description:
      'La Unidad 5 de Colina es la opción ideal para grupos o familias numerosas. Con 2 habitaciones que suman 4 camas matrimoniales, refrigerador y todo lo necesario para una estadía cómoda. Estacionamiento privado incluido y acceso al complejo Colina en la tranquila colonia Aguacatal. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 789,
    cleaningFee: 300,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 7,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Refrigerador', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'grupos', 'familiar'],
  },
  12155810: {
    isVisible: true,
    slug: 'colina-6a',
    name: 'Colina 6A',
    shortDescription:
      'Espacioso departamento familiar para hasta 7 personas. 3 habitaciones con 3 camas matrimoniales. Pet friendly, cocina equipada y estacionamiento privado.',
    description:
      'La Unidad 6A es la opción perfecta para familias o grupos que viajan juntos. Con tres habitaciones con camas matrimoniales, dos baños completos, amplia sala-comedor y cocina totalmente equipada. Ubicada en el 1er piso del complejo Colina en Aguacatal, con estacionamiento privado. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 789,
    cleaningFee: 300,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 7,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'familiar', 'grupos'],
  },
  12155811: {
    isVisible: true,
    slug: 'colina-estacionamiento',
    name: 'Colina Estacionamiento',
    shortDescription:
      'Departamento en planta baja con acceso directo, ideal para 1 a 2 personas. Sin escaleras, perfecto para movilidad reducida. Estacionamiento y WiFi incluidos.',
    description:
      'La unidad Estacionamiento del complejo Colina es perfecta para quienes buscan comodidad sin escaleras. Ubicada en planta baja con acceso directo, cocina equipada y estacionamiento privado. Ideal para viajeros con movilidad reducida o quienes prefieren la practicidad de la planta baja. En la tranquila colonia Aguacatal, cerca del Mercado La Rotonda y el centro de Xalapa. Pet friendly.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 549,
    cleaningFee: 200,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly', 'Planta baja'],
    tags: ['colinas', 'pareja', 'accesible'],
  },
  12298217: {
    isVisible: true,
    slug: 'colina-9',
    name: 'Colina 9',
    shortDescription:
      'Alojamiento familiar a 4 cuadras del CECAN. 2 habitaciones con 2 camas matrimoniales. Pet friendly, cocina equipada y estacionamiento privado.',
    description:
      'La Unidad 9 del complejo Colina se encuentra en el 3er piso del edificio en Aguacatal, con 2 habitaciones con camas matrimoniales, cocina equipada y estacionamiento privado. A 4 cuadras del Centro de Cancerología CECAN y 15 minutos caminando del centro histórico. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 669,
    cleaningFee: 250,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'familiar', 'pareja'],
  },
  12298218: {
    isVisible: true,
    slug: 'colina-7',
    name: 'Colina 7',
    shortDescription:
      'Alojamiento familiar céntrico a 4 cuadras del CECAN. 2 habitaciones con 2 camas matrimoniales. Pet friendly y estacionamiento privado.',
    description:
      'La Unidad 7 de Colina está ubicada en el 2do piso del edificio coral en Aguacatal, con 2 habitaciones con camas matrimoniales, cocina equipada y estacionamiento privado. A 4 cuadras del CECAN y 15 minutos del centro histórico. Ideal para familias o grupos de hasta 5 personas. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 669,
    cleaningFee: 250,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Pet friendly'],
    tags: ['colinas', 'familiar', 'pareja'],
  },
  12081652: {
    isVisible: true,
    slug: 'colina-14',
    name: 'Colina 14',
    shortDescription:
      'Penthouse climatizado en 5to piso con vistas panorámicas de Xalapa. 2 habitaciones con 2 camas matrimoniales. Pet friendly y cocina equipada.',
    description:
      'La Unidad 14 es el penthouse del complejo Colina, ubicado en el 5to piso con vistas panorámicas de Xalapa. Cuenta con aire acondicionado, 2 habitaciones con camas matrimoniales, cocina completamente equipada y estacionamiento privado. El único departamento del complejo con A/C. Pet friendly. Limpieza semanal gratuita en estancias mayores a 7 noches.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 919,
    cleaningFee: 350,
    extraGuestFeePerNight: 50,
    baseGuests: 2,
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 1,
    amenities: [
      'WiFi',
      'Cocina completa',
      'Estacionamiento',
      'TV',
      'Aire acondicionado',
      'Pet friendly',
      'Vista panorámica',
    ],
    tags: ['colinas', 'familiar', 'pareja', 'premium'],
  },
};
