import type { InternalProperty } from './types';

type CatalogEntry = Omit<
  InternalProperty,
  'id' | 'coverImageUrl' | 'checkinTime' | 'checkoutTime' | 'address' | 'latitude' | 'longitude'
> & { isVisible: boolean };

// Static enrichment data per Hostex property ID.
// coverImageUrl, checkinTime, checkoutTime, address, lat/lng come from Hostex API.
// Everything else is managed here until a proper CMS is in place.
export const PROPERTY_CATALOG: Record<number, CatalogEntry> = {
  12081652: {
    isVisible: true,
    slug: 'colina-14',
    name: 'Colinas del Café — Unidad 14',
    shortDescription:
      'Amplio departamento en complejo privado con vista al jardín y acceso a zona BBQ.',
    description:
      'Descansa en esta espaciosa unidad del complejo Colinas del Café, ubicado en la tranquila colonia Aguacatal de Xalapa. Disfruta de habitaciones luminosas, cocina completamente equipada y acceso al jardín compartido. A pocos minutos del centro histórico, museos y los mejores cafés de la ciudad.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_100,
    cleaningFee: 300,
    extraGuestFeePerNight: 150,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Zona BBQ', 'Jardín'],
    tags: ['colinas', 'familiar'],
  },
  12155808: {
    isVisible: true,
    slug: 'colina-4',
    name: 'Colinas del Café — Unidad 4',
    shortDescription: 'Acogedor departamento en zona residencial, cerca de todo en Xalapa.',
    description:
      'La Unidad 4 de Colinas del Café te ofrece todo lo necesario para una estadía perfecta. Ubicada en la colonia Aguacatal, rodeada de vegetación y con el clima fresco característico de Xalapa. Ideal para parejas o viajeros que buscan tranquilidad sin alejarse de la ciudad.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_000,
    cleaningFee: 250,
    extraGuestFeePerNight: 150,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Jardín'],
    tags: ['colinas', 'pareja'],
  },
  12155809: {
    isVisible: true,
    slug: 'colina-2',
    name: 'Colinas del Café — Unidad 2',
    shortDescription: 'Departamento luminoso con acceso a jardín privado en zona cafetalera.',
    description:
      'La Unidad 2 de Colinas del Café es perfecta para quienes buscan el equilibrio entre comodidad y naturaleza. Rodeada de jardines y con vistas al área verde del complejo. A pocos minutos del Parque Natura, el Museo de Antropología y el centro de Xalapa.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_000,
    cleaningFee: 250,
    extraGuestFeePerNight: 150,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Jardín'],
    tags: ['colinas', 'pareja'],
  },
  12155810: {
    isVisible: true,
    slug: 'colina-6a',
    name: 'Colinas del Café — Unidad 6A',
    shortDescription: 'La unidad más grande del complejo, ideal para grupos y familias de hasta 6.',
    description:
      'La Unidad 6A es la opción perfecta para familias o grupos que viajan juntos. Con tres habitaciones cómodas, dos baños completos, amplia sala-comedor y cocina totalmente equipada. El complejo Colinas del Café cuenta con jardín, zona de asadores y estacionamiento privado.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_400,
    cleaningFee: 400,
    extraGuestFeePerNight: 150,
    baseGuests: 4,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: [
      'WiFi',
      'Cocina completa',
      'Estacionamiento',
      'TV',
      'Zona BBQ',
      'Jardín',
      'Sala amplia',
    ],
    tags: ['colinas', 'familiar', 'grupos'],
  },
  12155811: {
    isVisible: false,
    slug: 'colina-estacionamiento',
    name: 'Colinas del Café — Estacionamiento',
    shortDescription: '',
    description: '',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 0,
    cleaningFee: 0,
    extraGuestFeePerNight: 0,
    baseGuests: 0,
    maxGuests: 0,
    bedrooms: 0,
    bathrooms: 0,
    amenities: [],
    tags: [],
  },
  12298217: {
    isVisible: true,
    slug: 'colina-9',
    name: 'Colinas del Café — Unidad 9',
    shortDescription:
      'Cómodo departamento con estacionamiento incluido y vistas al jardín del complejo.',
    description:
      'La Unidad 9 forma parte del querido complejo Colinas del Café en la colonia Aguacatal. Disfruta del clima perfecto de Xalapa desde un espacio acogedor, bien equipado y con todo lo que necesitas para sentirte como en casa. Perfecto para escapadas de fin de semana.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_050,
    cleaningFee: 250,
    extraGuestFeePerNight: 150,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Jardín'],
    tags: ['colinas', 'pareja', 'familiar'],
  },
  12298218: {
    isVisible: true,
    slug: 'colina-7',
    name: 'Colinas del Café — Unidad 7',
    shortDescription: 'Departamento tranquilo en complejo privado, a minutos del centro de Xalapa.',
    description:
      'La Unidad 7 de Colinas del Café es ideal para quienes buscan privacidad y tranquilidad. Con un ambiente relajado, decoración cálida y todos los servicios básicos. A 10 minutos del centro histórico, parques y restaurantes. El café con leche de Xalapa te espera cada mañana.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_000,
    cleaningFee: 250,
    extraGuestFeePerNight: 150,
    baseGuests: 2,
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV'],
    tags: ['colinas', 'pareja'],
  },
  12393467: {
    isVisible: true,
    slug: 'noviembre-20',
    name: 'Casa Noviembre 20',
    shortDescription:
      'Casa completa en colonia Modelo, a pasos de avenidas y vida urbana de Xalapa.',
    description:
      'Casa Noviembre 20 es una propiedad completa ubicada en la colonia Modelo, una de las zonas más activas y céntricas de Xalapa. Con amplio espacio, sala, comedor, cocina equipada y terraza, es perfecta para grupos o familias que quieren estar en el corazón de la ciudad. Restaurantes, tiendas y transporte a pasos.',
    neighborhood: 'Colonia Modelo',
    location: 'Colonia Modelo, Xalapa',
    pricePerNight: 1_400,
    cleaningFee: 400,
    extraGuestFeePerNight: 150,
    baseGuests: 4,
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Terraza', 'Sala amplia'],
    tags: ['céntrico', 'familiar', 'grupos'],
  },
  12454379: {
    isVisible: true,
    slug: 'colina-5',
    name: 'Colinas del Café — Unidad 5',
    shortDescription:
      'Encantadora unidad con jardín, ambiente cafetalero y vista al cerro de Macuiltépetl.',
    description:
      'La Unidad 5 de Colinas del Café combina comodidad y naturaleza en perfecta armonía. Con acceso al jardín del complejo, decoración cálida y vistas a la zona arbolada, esta unidad es perfecta para parejas o pequeñas familias. A pocos minutos del Parque Macuiltépetl y los mejores cafés de Xalapa.',
    neighborhood: 'Aguacatal',
    location: 'Aguacatal, Xalapa',
    pricePerNight: 1_100,
    cleaningFee: 300,
    extraGuestFeePerNight: 150,
    baseGuests: 3,
    maxGuests: 5,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Cocina completa', 'Estacionamiento', 'TV', 'Jardín'],
    tags: ['colinas', 'familiar', 'pareja'],
  },
};
